import { Allflag } from "./flag";
export const countries = [
  { name: "United Arab Emirates",id: 185, code: "AE", flag: Allflag.AE , dail_code: "+971"},
  { name: "Afghanistan",id: 1, code: "AF", flag: Allflag.AF , dail_code: "+93"},

  { name: "Albania" ,id: 2, code: "AL", flag: Allflag.AL , dail_code: "+355"},
  { name: "Algeria",id: 3, code: "DZ", flag: Allflag.DZ, dail_code: "+213" },
  { name: "Andorra", id: 4, code: "AD", flag: Allflag.AD , dail_code: "+376"},
  { name: "Angola",id: 5, code: "AO", flag: Allflag.AO , dail_code: "+244"},
  { name: "Antigua and Barbuda",id: 6, code: "AG", flag: Allflag.AG , dail_code: "+1268"},
  { name: "Argentina",id: 7, code: "AR", flag: Allflag.AR , dail_code: "+54"},
  { name: "Armenia",id: 8, code: "AM", flag: Allflag.AM , dail_code: "+374" },
  { name: "Australia",id: 9, code: "AU", flag: Allflag.AU , dail_code: "+61"},
  { name: "Austria", id: 10, code: "AT", flag: Allflag.AT , dail_code: "+43"},
  { name: "Azerbaijan", id: 11, code: "AZ", flag: Allflag.AZ , dail_code: "+994"},
  { name: "Bahamas",  id: 12,code: "BS", flag: Allflag.BS , dail_code: "+1242"},
  { name: "Bahrain",id: 13, code: "BH", flag: Allflag.BH , dail_code: "+973"},
  { name: "Bangladesh",id: 14, code: "BD", flag: Allflag.BD , dail_code: "+880"},
  { name: "Barbados",id: 15, code: "BB", flag: Allflag.BB , dail_code: "+1246"},
  { name: "Belarus", id: 16, code: "BY", flag: Allflag.BY , dail_code: "+375"},
  { name: "Belgium",id: 17, code: "BE", flag: Allflag.BE , dail_code: "+32"},
  { name: "Belize",  id: 18, code: "BZ", flag: Allflag.BZ , dail_code: "+501"},
  { name: "Benin", id: 19, code: "BJ", flag: Allflag.BJ , dail_code: "+229"},
  { name: "Bhutan",id: 20, code: "BT", flag: Allflag.BT , dail_code: "+975"},
  { name: "Bolivia",id: 21, code: "BO", flag: Allflag.BO , dail_code: "+591"},
  { name: "Bosnia and Herzegovina", id: 22, code: "BA", flag: Allflag.BA , dail_code: "+387"},
  { name: "Botswana",id: 23, code: "BW", flag: Allflag.BW , dail_code: "+267"},
  { name: "Brazil", id: 24, code: "BR", flag: Allflag.BR , dail_code: "+55"},
  { name: "Brunei Darussalam", id: 25, code: "BN", flag: Allflag.BN , dail_code: "+673"},
  { name: "Bulgaria", id: 26,code: "BG", flag: Allflag.BG , dail_code: "+359"},
  { name: "Burkina Faso",id: 27, code: "BF", flag: Allflag.BF , dail_code: "+226"},
  { name: "Burundi", id: 28, code: "BI", flag: Allflag.BI , dail_code: "+257"},
  { name: "Cambodia",id: 31, code: "KH", flag: Allflag.KH , dail_code: "+855"},
  { name: "Cameroon",id: 32, code: "CM", flag: Allflag.CM , dail_code: "+237"},
  { name: "Canada", id: 33, code: "CA", flag: Allflag.CA , dail_code: "+1"},
  { name: "Cabo Verde",id: 30, code: "CV", flag: Allflag.CV , dail_code: "+238"},
  { name: "Central African Republic",id: 34, code: "CF", flag: Allflag.CF , dail_code: "+236"},
  { name: "Chad",  id: 35,code: "TD", flag: Allflag.TD, dail_code: "+235" },
  { name: "Chile", id: 36,code: "CL", flag: Allflag.CL , dail_code: "+56"},
  { name: "China", id: 37, code: "CN", flag: Allflag.CN , dail_code: "+86"},
  { name: "Colombia", id: 38, code: "CO", flag: Allflag.CO , dail_code: "+57"},
  { name: "Comoros", id: 39, code: "KM", flag: Allflag.KM , dail_code: "+269"},
  
  {
    name: "Congo, Democratic Republic of the Congo",
    id: 40,
    code: "CD",
    flag: Allflag.CD,
    dail_code: "+243",
  },
  { name: "Costa Rica",id: 41, code: "CR", flag: Allflag.CR , dail_code: "+506"},
  { name: "Cote dIvoire" ,id: 29, code: "CI", flag: Allflag.CI, dail_code: "+225" },
  { name: "Croatia",  id: 42,code: "HR", flag: Allflag.HR , dail_code: "+385"},
  { name: "Cuba", id: 43, code: "CU", flag: Allflag.CU , dail_code: "+53"},
  { name: "Cyprus",id: 44, code: "CY", flag: Allflag.CY , dail_code: "+357"},
  { name: "Czech Republic",id: 45, code: "CZ", flag: Allflag.CZ , dail_code: "+420"},
  { name: "Denmark",id: 47, code: "DK", flag: Allflag.DK , dail_code: "+45"},
  { name: "Djibouti",  id: 48,code: "DJ", flag: Allflag.DJ,   dail_code: "+253" },
  { name: "Dominica", id: 49,code: "DM", flag: Allflag.DM , dail_code: "+1767"},
  { name: "Dominican Republic", id: 50, code: "DO", flag: Allflag.DO , dail_code: "+1849"},
  { name: "Ecuador",id: 51, code: "EC", flag: Allflag.EC , dail_code: "+593"},
  { name: "Egypt",id: 52, code: "EG", flag: Allflag.EG , dail_code: "+20"},
  { name: "El Salvador", id: 53,code: "SV", flag: Allflag.SV , dail_code: "+503"},
  { name: "Equatorial Guinea",id: 54, code: "GQ", flag: Allflag.GQ , dail_code: "+240"},
  { name: "Eritrea", id: 55, code: "ER", flag: Allflag.ER , dail_code: "+291"},
  { name: "Estonia",id: 56, code: "EE", flag: Allflag.EE , dail_code: "+372"},
  { name: "Ethiopia",id: 58, code: "ET", flag: Allflag.ET , dail_code: "+251"},
  
  { name: "Fiji",id: 59, code: "FJ", flag: Allflag.FJ , dail_code: "+679"},
  { name: "Finland",  id: 60,code: "FI", flag: Allflag.FI , dail_code: "+358"},
  { name: "France", id: 61, code: "FR", flag: Allflag.FR , dail_code: "+33"},
 
  { name: "Gabon", id: 62, code: "GA", flag: Allflag.GA , dail_code: "+241"},
  { name: "Gambia",  id: 63,code: "GM", flag: Allflag.GM , dail_code: "+220"},
  { name: "Georgia",id: 64, code: "GE", flag: Allflag.GE , dail_code: "+995"},
  { name: "Germany", id: 65, code: "DE", flag: Allflag.DE , dail_code: "+49"},
  { name: "Ghana", id: 66,code: "GH", flag: Allflag.GH , dail_code: "+233"},
 
  { name: "Greece", id: 67, code: "GR", flag: Allflag.GR , dail_code: "+30"},

  { name: "Grenada", id: 68, code: "GD", flag: Allflag.GD , dail_code: "+1473"},

  { name: "Guatemala",id: 69, code: "GT", flag: Allflag.GT , dail_code: "+502"},
  
  { name: "Guinea",id: 70, code: "GN", flag: Allflag.GN , dail_code: "+224"},
  { name: "Guinea-Bissau",  id: 71,code: "GW", flag: Allflag.GW , dail_code: "+245"},
  { name: "Guyana",id: 72, code: "GY", flag: Allflag.GY , dail_code: "+592"},
  { name: "Haiti",id: 73, code: "HT", flag: Allflag.HT , dail_code: "+509"},
  { name: "Honduras",id: 75, code: "HN", flag: Allflag.HN , dail_code: "+504"},
  
  { name: "Hungary",id: 76, code: "HU", flag: Allflag.HU , dail_code: "+36"},
  { name: "Iceland", id: 77, code: "IS", flag: Allflag.IS , dail_code: "+354"},
  { name: "India", id: 78,code: "IN", flag: Allflag.IN , dail_code: "+91"},
  { name: "Indonesia",id: 79, code: "ID", flag: Allflag.ID , dail_code: "+62"},
  { name: "Iran, Islamic Republic of",id: 80, code: "IR", flag: Allflag.IR , dail_code: "+98"},
  { name: "Iraq", id: 81, code: "IQ", flag: Allflag.IQ , dail_code: "+964"},
  { name: "Ireland",id: 82,code: "IE", flag: Allflag.IE , dail_code: "+353"},
  
  { name: "Israel",id: 83, code: "IL", flag: Allflag.IL , dail_code: "+972"},

  { name: "Jamaica",id: 85, code: "JM", flag: Allflag.JM , dail_code: "+1876"},
  { name: "Japan",id: 86, code: "JP", flag: Allflag.JP , dail_code: "+81"},
  
  { name: "Jordan",id: 87, code: "JO", flag: Allflag.JO , dail_code: "+962"},
  { name: "Kazakhstan",id: 88, code: "KZ", flag: Allflag.KZ , dail_code: "+7"},
  { name: "Kenya",id: 89, code: "KE", flag: Allflag.KE , dail_code: "+254"},

  {
    name: "North-Korea, Democratic People's Republic of",
    id: 128,
    code: "KP",
    flag: Allflag.KP,
    dail_code: "+850",
  },
  { name: "South-Korea, Republic of", id: 163, code: "KR", flag: Allflag.KR , dail_code: "+82"},

  { name: "Kuwait", id: 91, code: "KW", flag: Allflag.KW , dail_code: "+965"},
  { name: "Kyrgyzstan", id: 92, code: "KG", flag: Allflag.KG , dail_code: "+996"},
  { name: "Lao People's Democratic Republic",id: 93, code: "LA", flag: Allflag.LA , dail_code: "+856"},
  { name: "Latvia", id: 94, code: "LV", flag: Allflag.LV , dail_code: "+371"},
  { name: "Lebanon", id: 95, code: "LB", flag: Allflag.LB , dail_code: "+961"},
  { name: "Lesotho", id: 96, code: "LS", flag: Allflag.LS , dail_code: "+266"},
  { name: "Liberia",id: 97, code: "LR", flag: Allflag.LR , dail_code: "+231"},
  { name: "Libyan Arab Jamahiriya",id: 98, code: "LY", flag: Allflag.LY , dail_code: "+218"},
  { name: "Liechtenstein",id: 99, code: "LI", flag: Allflag.LI , dail_code: "+423"},
  { name: "Lithuania", id: 100, code: "LT", flag: Allflag.LT , dail_code: "+370"},
  { name: "Luxembourg",id: 101, code: "LU", flag: Allflag.LU , dail_code: "+352"},
 
  {
    name: "North-Macedonia",
    id: 129,
    code: "MK",
    flag: Allflag.MK,
    dail_code: "+389",

  },
  { name: "Madagascar", id: 102, code: "MG", flag: Allflag.MG , dail_code: "+261"},
  { name: "Malawi",id: 103, code: "MW", flag: Allflag.MW , dail_code: "+265"},
  { name: "Malaysia",id: 104, code: "MY", flag: Allflag.MY , dail_code: "+60"},
  { name: "Maldives",id: 105, code: "MV", flag: Allflag.MV , dail_code: "+960"},
  { name: "Mali", id: 106, code: "ML", flag: Allflag.ML , dail_code: "+223"},
  { name: "Malta", id: 107, code: "MT", flag: Allflag.MT , dail_code: "+356"},
  { name: "Mauritius", id: 110, code: "MU", flag: Allflag.MU , dail_code: "+230"},
  { name: "Mexico", id: 111, code: "MX", flag: Allflag.MX , dail_code: "+52"},
  { name: "Micronesia, Federated States of",id: 112, code: "FM", flag: Allflag.FM , dail_code: "+691"},
  { name: "Moldova, Republic of",id: 113, code: "MD", flag: Allflag.MD , dail_code: "+373"},
  { name: "Monaco",id: 114, code: "MC", flag: Allflag.MC , dail_code: "+377"},
  { name: "Mongolia", id: 115, code: "MN", flag: Allflag.MN , dail_code: "+976"},
  { name: "Montenegro", id: 116, code: "ME", flag: Allflag.ME , dail_code: "+382"},
  { name: "Morocco",  id: 117,code: "MA", flag: Allflag.MA , dail_code: "+212"},
  { name: "Mozambique",id: 118, code: "MZ", flag: Allflag.MZ , dail_code: "+258"},
  { name: "Myanmar", id: 119, code: "MM", flag: Allflag.MM , dail_code: "+95"},
  { name: "Namibia", id: 120,code: "NA", flag: Allflag.NA , dail_code: "+264"},

  { name: "Nepal",id: 122, code: "NP", flag: Allflag.NP , dail_code: "+977"},
  { name: "Netherlands", id: 123, code: "NL", flag: Allflag.NL , dail_code: "+31"},
  

  { name: "New Zealand", id: 124,code: "NZ", flag: Allflag.NZ , dail_code: "+64"},
  { name: "Nicaragua",id: 125, code: "NI", flag: Allflag.NI , dail_code: "+505"},
  { name: "Niger",id: 126, code: "NE", flag: Allflag.NE , dail_code: "+227"},
  { name: "Nigeria",id: 127, code: "NG", flag: Allflag.NG , dail_code: "+234"},

  { name: "Norway",id: 130, code: "NO", flag: Allflag.NO , dail_code: "+47"},
  { name: "Oman",id: 131, code: "OM", flag: Allflag.OM  , dail_code: "+968"},
  { name: "Pakistan", id: 132, code: "PK", flag: Allflag.PK , dail_code: "+92"},
  { name: "Palau", id: 133, code: "PW", flag: Allflag.PW , dail_code: "+680"},
  { name: "Panama",id: 135, code: "PA", flag: Allflag.PA , dail_code: "+507"},
  { name: "Papua New Guinea",id: 136, code: "PG", flag: Allflag.PG , dail_code: "+675"},
  { name: "Paraguay",id: 137, code: "PY", flag: Allflag.PY , dail_code: "+595"},
  { name: "Peru",id: 138, code: "PE", flag: Allflag.PE , dail_code: "+51"},
  { name: "Philippines",  id: 139, code: "PH", flag: Allflag.PH , dail_code: "+63"},

  { name: "Poland", id: 140, code: "PL", flag: Allflag.PL , dail_code: "+48"},
  { name: "Portugal",id: 141, code: "PT", flag: Allflag.PT , dail_code: "+351"},
  { name: "Qatar",id: 142, code: "QA", flag: Allflag.QA , dail_code: "+974"},

  { name: "Romania", id: 143,code: "RO", flag: Allflag.RO , dail_code: "+40"},
  { name: "Russian Federation", id: 144, code: "RU", flag: Allflag.RU , dail_code: "+7"},
  { name: "Rwanda", id: 145, code: "RW", flag: Allflag.RW , dail_code: "+250"},

  { name: "Saint Kitts and Nevis",id: 146, code: "KN", flag: Allflag.KN , dail_code: "+1869"  },
  { name: "Saint Lucia", id: 147, code: "LC", flag: Allflag.LC , dail_code: "+1758"},

  { name: "Saint Vincent and the Grenadines", id: 148, code: "VC", flag: Allflag.VC , dail_code: "+1784"},
  { name: "Samoa",id: 149, code: "WS", flag: Allflag.WS , dail_code: "+685"},
  { name: "San Marino",id: 150, code: "SM" , flag: Allflag.SM , dail_code: "+378"},
  { name: "Sao Tome and Principe",id: 151, code: "ST", flag: Allflag.ST , dail_code: "+239"},
  { name: "Saudi Arabia",  id: 152, code: "SA", flag: Allflag.SA , dail_code: "+966"},
  { name: "Senegal", id: 153, code: "SN", flag: Allflag.SN , dail_code: "+221"},
  { name: "Serbia",id: 154, code: "RS", flag: Allflag.RS , dail_code: "+381"},

  { name: "Seychelles",   id: 155, code: "SC", flag: Allflag.SC , dail_code: "+248"},
  { name: "Sierra Leone",     id: 156,  code: "SL", flag: Allflag.SL , dail_code: "+232"},
  { name: "Singapore",id: 157, code: "SG", flag: Allflag.SG , dail_code: "+65"},

  { name: "Slovakia",id: 158, code: "SK", flag: Allflag.SK  , dail_code: "+421"},
  { name: "Slovenia",id: 159, code: "SI", flag: Allflag.SI , dail_code: "+386"},
  { name: "Solomon Islands",id: 160, code: "SB", flag: Allflag.SB , dail_code: "+677"},
  { name: "Somalia",id: 161, code: "SO", flag: Allflag.SO , dail_code: "+252"},
  { name: "South Africa",id: 162, code: "ZA", flag: Allflag.ZA , dail_code: "+27"},

  { name: "Spain",id: 165, code: "ES", flag: Allflag.ES , dail_code: "+34"},
  { name: "Sri Lanka",id: 166, code: "LK", flag: Allflag.LK , dail_code: "+94"},
  { name: "Sudan",id: 167, code: "SD", flag: Allflag.SD , dail_code: "+249"},
  { name: "Suriname", id: 168, code: "SR", flag: Allflag.SR , dail_code: "+597"},

  { name: "Swaziland",id: 57, code: "SZ", flag: Allflag.SZ , dail_code: "+268"},
  { name: "Sweden", id: 169, code: "SE", flag: Allflag.SE , dail_code: "+46"},
  { name: "Switzerland",id: 170, code: "CH", flag: Allflag.CH , dail_code: "+41"},
  { name: "Syrian Arab Republic",id: 171, code: "SY", flag: Allflag.SY , dail_code: "+963"},
  { name: "Tajikistan",id: 172, code: "TJ", flag: Allflag.TJ , dail_code: "+992"},
  { name: "Tanzania, United Republic of",id: 173, code: "TZ", flag: Allflag.TZ , dail_code: "+255"},
  { name: "Thailand", id: 174, code: "TH", flag: Allflag.TH , dail_code: "+66"},
  { name: "Timor-Leste", id: 175, code: "TL", flag: Allflag.TL , dail_code: "+670"},
  { name: "Togo", id: 176, code: "TG", flag: Allflag.TG , dail_code: "+228"},

  { name: "Tonga",id: 177, code: "TO", flag: Allflag.TO , dail_code: "+676"},
  { name: "Trinidad and Tobago", id: 178, code: "TT", flag: Allflag.TT , dail_code: "+1868"},
  { name: "Tunisia", id: 179, code: "TN", flag: Allflag.TN , dail_code: "+216"},
  { name: "Turkey", id: 180,code: "TR", flag: Allflag.TR , dail_code: "+90"},
  { name: "Turkmenistan", id: 181, code: "TM", flag: Allflag.TM , dail_code: "+993"},
  { name: "Tuvalu",id: 182, code: "TV", flag: Allflag.TV , dail_code: "+688"},
  { name: "Uganda",id: 183, code: "UG", flag: Allflag.UG , dail_code: "+256"},
  { name: "Ukraine",id: 184, code: "UA", flag: Allflag.UA , dail_code: "+380"},

  { name: "United Kingdom", id: 186, code: "GB", flag: Allflag.GB , dail_code: "+44"},
  { name: "United States of America", id: 187, code: "US", flag: Allflag.US , dail_code: "+1"},
  { name: "Uruguay",id: 188, code: "UY", flag: Allflag.UY , dail_code: "+598" },
  { name: "Uzbekistan", id: 189, code: "UZ", flag: Allflag.UZ , dail_code: "+998"},
  { name: "Vanuatu", id: 190, code: "VU", flag: Allflag.VU , dail_code: "+678"},
  { name: "Venezuela",id: 191, code: "VE", flag: Allflag.VE , dail_code: "+58"},
  { name: "Vietnam",id: 192, code: "VN", flag: Allflag.VN , dail_code: "+84"},
  { name: "Yemen", id: 193, code: "YE", flag: Allflag.YE , dail_code: "+967"},
  { name: "Zambia", id: 194, code: "ZM", flag: Allflag.ZM  , dail_code: "+260"},
  { name: "Zimbabwe",id: 195, code: "ZW", flag: Allflag.ZW , dail_code: "+263" },
];

// countryPhoneCodes
