export type Experience = {
  company_title: string;
  start_date: string;
  current_employer: string;
  end_date: string;
  job_desc: string;
};

export type Practitioner = {
  user_id: number;
  first_name: string;
  last_name: string;
  slug: string;
  experiences: Experience[];
  avatar: string;
  clients_no: string;
  short_desc: string;
  years_of_practice: number;
  service_id: number;
  education: string;
  rating: number | null;
  user_tags: string;
  approaches: string;
  languages: string;
  appointments_count: number;
  service_count: number;
  service_price: number;
  free_intro: number;
  five_dollar_intro: number;
};

export type PractitionerData = {
  practitioners: Practitioner[];
};

export type PractitionerDetail = {
  userOBJ: {
    id: number;
    first_name: string;
    last_name: string;
    slug: string;
    email: string;
    location_id: number;
    city_id: number | null;
    verification_code: string;
    user_verified: number;
    package_expiry: string | null;
    created_at: string;
    updated_at: string;
    languages_spoken: string;
    countries_worked: string | null;
    gender: string;
    dob: string;
    phone: string;
    account_deleted: string;
    deleted_at: string | null;
    added_by_pract: string;
    profile_views: string;
    block: number;
    reason: string | null;
    event_access: string;
    force_password_change: number;
    designation: string | null;
    coverage_tier_id: number | null;
    ministry: string | null;
    chearful_percentage: null;
  };
  avg_rating: number;
  user_feedback: any[];
  total_feedbacks: number;
  languages: {
    id: number;
    user_id: number;
    language_id: number;
    created_at: string;
    updated_at: string;
  }[];
  short_desc: string;
  experiance: string;
  education: {
    id: number;
    user_id: number;
    title: string;
    start_year: number | null;
    end_year: number | null;
    is_pursuing: number;
    created_at: string;
    updated_at: string;
  };
  gender_title: string;
  approach_tags: string[];
  user_meta : UserMeta;
  services: {
    id: number;
    user_id: number;
    service_id: number;
    price: number;
    duration: number;
    is_active: number;
    created_at: string;
    updated_at: string;
  }[];
};


type UserMeta = {
  id: number;
  user_id: number;
  experiences: string;
  specializations: null | string;
  memberships: null | string;
  educations: string;
  awards: string;
  services: string;
  free_service_session: number;
  professional_licenses: string;
  professional_registrations: string;
  avatar: string;
  avatar_date: string;
  gov_issued_docx: string;
  license_doc_uploads: string;
  banner: null | string;
  gender: null | string;
  gender_title: string;
  sub_heading: null | string;
  tagline: null | string;
  short_desc: string;
  description: null | string;
  delete_reason: null | string;
  delete_description: null | string;
  payout_id: null | number;
  profile_searchable: null | string;
  weekly_alerts: null | string;
  disable_account: null | string;
  message_alerts: null | string;
  verify_medical: string;
  consultation_fee: null | number;
  saved_hospitals: null | string;
  saved_doctors: null | string;
  saved_articles: null | string;
  downloads: string;
  address: null | string;
  longitude: null | string;
  latitude: null | string;
  verify_registration: number;
  recommendation: null | string;
  votes: number;
  available_days: string;
  working_time: null | string;
  liked_answers: string;
  starting_price: number;
  payout_settings: string;
  created_at: string;
  updated_at: string;
  gallery: string;
  gallery_videos: string;
  doctor_cats: string;
  doctor_approach_therapies: string;
  tags: null | string;
  clients_no: string;
  years_of_practice: number;
  is_licensed: number;
  resume: null | string;
  resume_date: null | string;
  certificates: string;
  timezone: string;
  timezone_offset: string;
  emr_name: null | string;
  emr_email: null | string;
  emr_phone: null | string;
  emr_relation: null | string;
  hourly_rate: null | number;
  languages_preference: string;
  gender_preference: string;
  change_coach: null | string;
};
