export const Colors = {
  //     BtnColor: "#91A362",
  //   Primary: "#1E5542",
  //   Secondary: "#EDF3DD",
  //   SwitchButtonColor: "#E8E8E8",
  //   White: "#FFFEFE",
  //   ContColor: "#D9E7C9",
  //   BtnCont: "#EFF3F2",
  //   OffWhiteCont: "#F2F2F2",
  //   MenuText: "#1D1A0E",
  //   Error: "#FF8383",
  //   InputBg: "#EFF3F2",
  //   Muted: "#989898",

  primaryLight: '#91A362',
  primary: '#1E5542',
  secondary: '#EDF3DD',
  //   SwitchButtonColor: '#E8E8E8',
  white: '#FFFEFE',
  contrast: '#D9E7C9',
  //   BtnCont: '#EFF3F2',
  light: '#F2F2F2',
  black: '#1D1A0E',
  error: '#FF8383',
  placeholder: '#EFF3F2',
  muted: '#989898',
};

export const Fonts = {
  Mulish: {
    200: 'Mulish-ExtraLight',
    300: 'Mulish-Light',
    400: 'Mulish-Regular',
    500: 'Mulish-Medium',
    600: 'Mulish-SemiBold',
    700: 'Mulish-Bold',
    800: 'Mulish-ExtraBold',
    900: 'Mulish-Black',
    Italic: {
      200: 'Mulish-ExtraLightItalic',
      300: 'Mulish-LightItalic',
      400: 'Mulish-Italic',
      500: 'Mulish-MediumItalic',
      600: 'Mulish-SemiBoldItalic',
      700: 'Mulish-BoldItalic',
      800: 'Mulish-ExtraBoldItalic',
      900: 'Mulish-BlackItalic',
    },
  },
  Nunito: {
    200: 'Nunito-ExtraLight',
    300: 'Nunito-Light',
    400: 'Nunito-Regular',
    500: 'Nunito-Medium',
    600: 'Nunito-SemiBold',
    700: 'Nunito-Bold',
    800: 'Nunito-ExtraBold',
    900: 'Nunito-Black',
    Italic: {
      200: 'Nunito-ExtraLightItalic',
      300: 'Nunito-LightItalic',
      400: 'Nunito-Italic',
      500: 'Nunito-MediumItalic',
      600: 'Nunito-SemiBoldItalic',
      700: 'Nunito-BoldItalic',
      800: 'Nunito-ExtraBoldItalic',
      900: 'Nunito-BlackItalic',
    },
  },
  Roboto: {
    300: 'Roboto-Light',
    400: 'Roboto-Regular',
    500: 'Roboto-Medium',
    700: 'Roboto-Bold',
    900: 'Roboto-Black',
    Italic: {
      300: 'Roboto-LightItalic',
      400: 'Roboto-Italic',
      500: 'Roboto-MediumItalic',
      700: 'Roboto-BoldItalic',
      900: 'Roboto-BlackItalic',
    },
  },
};
